exports.appString = {
    USERNAME_REQUIRED: "UserName Is Required",
    EMAIL_REQUIRED: "Email Is Required",
    COUNTRYCODE_REQUIRED: "Country Code Is Required",
    Contact_REQUIRED: "Contact  Is Required",
    EMAILALREDY_REGISTERED: "Email Is Already Registered",
    DOCTOR_RGISTRATION_SUCCESSFULL: "Doctor Registration Successfull",
    SERVER_ERROR: "Server Error",
    DOCTOR_REGISTRATION_SUCCESSFULL_VERIFIED: "Doctor Registration Verfied Successfull",
    COUNTRY_CODECONTACT_NUMBER_REQUIRED: "CountryCode & Contact Number is required",
    CODEMUSTSTARTSWITHADDITIONOPERATORS: "Code Must Starts With + ",
    INVALID_PHONEFORMAT: "invalid Phone Number Format",
    LOGIN_SUCCESS_VERIFIED: "Login Verifiaction Is Successfully",
    OTP_VERIFICATION_FAILED: "Otp Verfication is Failed",
    OTP_SENT_SUCCESS: "OTP sent to your email.",
    PATIENTS_RGISTRATION_SUCCESSFULL: "Patient Registration Successfull",
    PATIENTS_REGISTRATION_SUCCESSFULL_VERIFIED: "Patients Verfied Successfully",
    LOGIN_FAILED: "LogIn Failed",
    INVALID_CREDENTIALS: "Invalid Credentials",
    INVALID_OR_EXPIRED_OTP: "Invalid & Expried otp",
    PATIENT_NOT_FOUND: "pATIENT nOt found ",
    Forbidden: "You are Unauthorized",
    ADMINSETTING_NOT_FOUND: "Admin Setting Not found",
    STEPSCREATED_SUCCESSFULLY:"Steps Created Successfully",
    REQUIRED_FIELDS:"Please provide all the required fields",
    ADMINSETTING_UPDATED:"Settings updated successfully",
    DOCTORID_NOT_FOUND:"Doctor Id Not Found",

    ADMIN_SETTINGS_MODEL: "AdminSetting",
    ADMIN_MODEL: "Admin",
    DOCTOR_MODEL: "Doctor",
    PATIENT_MODEL: "Patients"
}